name: Save Waka 'Readme.md'

on:
  schedule:
    # 매주 일요일 오전 12:10에 업데이트
    - cron: '10 15 * * 0'
    # cron: '00 15 * * *'로 하면 한국 시간 기준으로 오전 12:00에 업데이트
  workflow_dispatch:
jobs:
  save-readme:
    name: Save Readme every Sunday
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!' > save.md
  
