name: Save Waka 'Readme.md'

on:
  schedule:
    # 매주 일요일 오전 12:10에 업데이트
    - cron: '10 15 * * 0'
    # cron: '00 15 * * *'로 하면 한국 시간 기준으로 오전 12:00에 업데이트
  workflow_dispatch:
jobs:
  build:
    name: Save Readme every Sunday
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10 
        uses: actions/setup-python@v3 # setup-python
        with:
          python-version: "3.10" # 3.10버전 파이썬 사용
      - name: Install dependencies # 1) 스크립트에 필요한 dependency 설치
        run: |
          python -m pip install --upgrade pip
      - name: Run save-readme.py # 2) save-readme.py 실행
        working-directory: script
        run: |
          python save-readme.py
      - name: Commit changes # 3) 추가된 파일 commit
        run: |
          git config --global user.name 'jung0115' # 유저명
          git config --global user.email 'jungim7490@gmail.com' # 유저 이메일
          git add -A
          git commit -m "save #3 : README.md for WakaTime lastweek" # 커밋 메시지
      - name: Push changes # 4) main에 푸시
        run: |
          git push
    
